### ISSUE TITLE
Critical Vulnerabilities

### ISSUE THREAD

**Issue by vishrantgupta** [bitnami/bitnami-docker-cert-manager#6]
### Name and Version

bitnami / bitnami-docker-cert-manager

### What steps will reproduce the bug?

Attached are the list of vulnerabilities in the bitnami / bitnami-docker-cert-manager docker imag
[vulnerabilities.pdf](https://github.com/bitnami/bitnami-docker-cert-manager/files/8287713/vulnerabilities.pdf)
e

### What do you see instead?

No vulnerabilities

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a daily basis, this kind of CVE will be reported while there is not a new version patching the issue in the OS or the application.

```console
$ trivy image --ignore-unfixed --vuln-type os bitnami/cert-manager
2022-03-17T16:13:05.812Z	INFO	Need to update DB
2022-03-17T16:13:05.812Z	INFO	Downloading DB...
26.53 MiB / 26.53 MiB [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 11.90 MiB p/s 2s
2022-03-17T16:13:09.823Z	INFO	Detected OS: debian
2022-03-17T16:13:09.823Z	INFO	Detecting Debian vulnerabilities...

bitnami/cert-manager (debian 10.11)
===================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```


You can find more info in [this blog post](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Open Source/Community Catalog is based on Debian but Bitnami/VMware provides a custom container and Helm Charts catalog based on the desired base image (generic distro or custom golden image) through [VMware Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog), which can have a different version or release cadence for system packages.

**Comment by vishrantgupta** [comment]
Hi @carrodher, thanks for looking into it, cert-manager has released the latest version https://github.com/cert-manager/cert-manager/issues/4951 which provides a fix for the go-lang vulnerability, is it possible to adopt the latest cert-manager patch?

**Comment by carrodher** [comment]
The latest version (1.7.2) was published some hours ago, see https://github.com/bitnami/bitnami-docker-cert-manager/commit/3faf52bdf2c513e33a97b5788c4535c4c8e89646

**Comment by vishrantgupta** [comment]
Hi @carrodher, I scanned the latest image https://github.com/bitnami/bitnami-docker-cert-manager/commit/3faf52bdf2c513e33a97b5788c4535c4c8e89646 the application vulnerabilities are removed, the OS vulnerability still needs a fix.
[cert_manage_v.pdf](https://github.com/bitnami/bitnami-docker-cert-manager/files/8339210/cert_manage_v.pdf)

Is it possible to change the base image?

**Comment by carrodher** [comment]
The Bitnami Application Catalog (OpenSource) is based on Debian 10 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on different base images (generic OS such as Debian, CentOS, PhotonOS, Ubuntu, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog)

**Comment by vishrantgupta** [comment]
The vulnerabilities are still there.

**Comment by carrodher** [comment]
Hi again,

Unfortunately, those security vulnerabilities **are not fixed by the OS** itself, so although we built the images on a daily basis, this kind of CVE will be reported while there is not a new version patching the issue in the OS.


Running the CVE scanner with the `--ignore-unfixed` flag, there are no CVEs reported:

```console
$ trivy image --ignore-unfixed bitnami/cert-manager
2022-04-09T08:02:20.519Z	INFO	Detected OS: debian
2022-04-09T08:02:20.519Z	INFO	Detecting Debian vulnerabilities...
2022-04-09T08:02:20.544Z	INFO	Number of language-specific files: 0

bitnami/cert-manager (debian 10.12)
===================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

I'm closing this issue since we can't do anything in order to fix it apart from releasing the images on a daily basis to use the latest version of the OS, that is something we're already doing.

**Comment by vishrantgupta** [comment]
Hmm, I would appreciated if there would have been a better fix for the critical vulnerabilities than closing it with "are not fixed by the OS", AFAIK VMware has a SLO to apply the patch to critical vulnerabilities w/in 48 hours.

`trivy` is not the tool that VMware maintain for vulnerabilities scan, but, if you have access you can check the internal scanning tool tool https://appcheck.eng.vmware.com/#/product/389274/analysis which reports the following critical vulnerabilities:

```
CVE-2022-23218
CVE-2022-23219
CVE-2021-35942
CVE-2022-22623
CVE-2019-9893
```

in these executables:

```
glibc2.28-10+deb10u1
curl7.64.0-4+deb10u2
libseccomp2.3.3-4
```

Can you try changing the base OS? If that's not possible what is the possible solution?

cc: @recena

**Comment by vishrantgupta** [comment]
The issue was raised so that all the critical vulnerabilities that are reported by the VMware scan tool are fixed, IMO the issue is not resolved and should remain open until there is a solution.

**Comment by carrodher** [comment]
Please note in GitHub we provide support for the Public/Open Source Bitnami Application Catalog (BAC) which is based on Debian 10 (that is a stable/LTS version of this distro).
As the information provided in this forum is public, we use opensource tools for scanning the container images, in that way all the users can see the results and logs, if you internally use any other VMware tool it is fine, but those private reports are not useful in a public forum like this one, that's why I always use `trivy`.

As I mentioned before, this public catalog is based on Debian 10 and we release the container images on a daily basis in order to include the latest version of the system packages, if there are CVEs not fixed by this distro or this specific version you can use the VMware Application Catalog (VAC).
Through [VMware Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog), container images are built on top of the desired base image selected by the user (Debian, Ubuntu, PhotonOS, or CentOS). Those distros or distro versions can have a different version or release cadence for the system packages which can cause some of these CVEs are not present.

Due to that reason, this Issue will be maintained as closed. At this moment the Bitnami Application Catalog (BAC) is based on Debian 10 and those CVEs are related to system packages, we can't do anything else here. Please take a look at  [VMware Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog) (VAC) if you need a different distro.
